In [1]:
import pandas as pd
import numpy as np
import os
from collections import Counter

In [2]:
l1 = r"C:/Users/shubh/Desktop/1dcnn/AEEEM"
l2 = r"C:/Users/shubh/Desktop/1dcnn/AEEEM_boruta/"
l3 = r"C:\Users\shubh\Desktop\XGB DNN\df after fs\AEEEM"

In [3]:
f1 =[]
f2=[]
f3 = []
fn =[]
r1=[]
r2 =[]
r3 =[]
o =[]
p=[]
for f in os.listdir(l1):
    df = pd.read_csv(os.path.join(l1,f))
    f1.append(df.shape[1])
    r1.append(df.shape[0])
    fn.append(f.split(".csv")[0])
    o.append(Counter(df.iloc[:,-1])[1])
    k=Counter(df.iloc[:,-1])[1]/df.shape[0]*100
    p.append(k)

for fff in os.listdir(l2):
    df = pd.read_csv(os.path.join(l2,fff))
    f3.append(df.shape[1]-1)
    r3.append(df.shape[0])
dframe = pd.concat([pd.Series(r1),pd.Series(o),pd.Series(p),pd.Series(f1),pd.Series(f3)],axis=1)
dframe.index =fn
dframe.columns =['No. of Samples','No. of Defective samples','Data Imbalance','Original No. of features','CorrBoost Features']
dframe.to_csv('ds analysis.csv')

In [4]:
dframe

,No. of Samples,No. of Defective samples,Data Imbalance,Original No. of features,CorrBoost Features
EQ,324,129,39.814815,61,18
JDT,997,206,20.661986,61,26
Lucene,691,64,9.261939,61,10
MyLyn,1862,245,13.157895,61,28
PDE,1497,209,13.961256,61,19

In [ ]:
o

In [4]:

loc = r"C:\Users\shubh\Desktop\XGB DNN\1407\Dataset"
for f in os.listdir(loc):
    df = pd.read_csv(os.path.join(loc,f))
    print(df.shape)
    df.columns = [*df.columns[:-1], 'Defective']
    df['Defective'] = df['Defective'].map({'Y': 1, 'N': 0})
    
    df = df.drop_duplicates()
    print(df.shape)

(327, 38)
(327, 38)
(7782, 22)
(7782, 22)
(1183, 22)
(1183, 22)
(194, 40)
(194, 40)
(1988, 39)
(1988, 39)
(125, 40)
(125, 40)
(253, 38)
(253, 38)
(705, 38)
(705, 38)
(745, 37)
(745, 37)
(1077, 38)
(1077, 38)
(1287, 38)
(1287, 38)
(1711, 39)
(1711, 39)

In [24]:
df

,LOC_BLANK,BRANCH_COUNT,CALL_PAIRS,LOC_CODE_AND_COMMENT,LOC_COMMENTS,CONDITION_COUNT,CYCLOMATIC_COMPLEXITY,CYCLOMATIC_DENSITY,DECISION_COUNT,DESIGN_COMPLEXITY,...,NODE_COUNT,NORMALIZED_CYLOMATIC_COMPLEXITY,NUM_OPERANDS,NUM_OPERATORS,NUM_UNIQUE_OPERANDS,NUM_UNIQUE_OPERATORS,NUMBER_OF_LINES,PERCENT_COMMENTS,LOC_TOTAL,Defective
0,3,11,2,1,4,16,6,0.19,8,4,...,18,0.14,38,51,21,19,43,13.89,32,1
1,6,17,2,0,3,24,9,0.16,8,4,...,19,0.13,97,132,35,18,72,5.00,57,0
2,0,11,5,3,6,20,6,0.19,10,6,...,20,0.15,48,58,21,11,40,23.68,32,0
3,1,17,2,1,17,24,9,0.14,8,5,...,21,0.11,83,188,15,17,83,22.50,63,0
4,7,17,4,0,7,30,9,0.23,14,8,...,29,0.16,69,94,24,13,56,14.89,40,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1706,0,1,1,0,0,0,1,0.50,0,1,...,3,0.25,1,7,1,6,4,0.00,2,0
1707,0,1,0,0,0,0,1,0.20,0,1,...,2,0.11,8,9,8,3,9,0.00,5,0
1708,1,33,0,4,11,40,17,0.39,8,1,...,28,0.26,57,92,15,11,66,27.27,44,0
1709,20,33,3,8,16,52,17,0.14,20,8,...,46,0.11,158,265,37,21,157,17.78,119,1
1710,2,1,1,0,1,0,1,0.33,0,1,...,3,0.11,1,6,1,5,9,25.00,3,0